### PR TITLE
44626 remove legacy indexing code

### PR DESCRIPTION
**Pull request by alfinkel**
This PR removes all legacy indexing/query code as well as any references to the legacy code throughout CDTDatastore.  Details follow:

- Remove legacy indexing tests
- Update `SetUpDatastore` test to use new query logic
- Update the sample app project to use new query logic. `CDTAppDelegate` and `CDTViewController` were changed.  `CDTCompletedIndexer` was removed.
- Remove `indexing` group and all classes included
- Remove legacy references from `CloudantSync.h` 

BugID: 44626
reviewer @mikerhodes
reviewer @tomblench

### CODE REVIEW

**Comment by tomblench** [comment]
Also need to remove doc/index-query.md and update doc/query.md to remove the introductory para referencing this legacy document.

**Comment by tomblench** [comment]
It looks like CDTINDEX_LOG_CONTEXT is no longer used - should we remove all references?

Also I see that CDTQLogging.h has been carried over from the time when this was a separate project. Ideally this could now be dropped and we could merge `CDTQ_LOGGING_CONTEXT 17` into `CDTLogging.h`. Or is this something for another PR?

**Comment by tomblench** [comment]
ReplicationAcceptance.m still has a reference to `CDTIndexManager` in `testPullLotsOfOneRevDocumentsIndexed`. This will cause the build for ReplicationAcceptance to fail. It can probably be removed.

**Comment by alfinkel** [comment]
In reference to https://github.com/cloudant/CDTDatastore/pull/116#issuecomment-85904363:  FB case 45650 (BugID: 45650) has been opened to address the merging of the logging headers at a later date.

**Comment by alfinkel** [comment]
In reference to https://github.com/cloudant/CDTDatastore/pull/116#issuecomment-85900447:  An FB case (BugID: 44627) already exists for a migration doc which will include the clean up of the query.md and the index-query.md files.  This update will be coming shortly in a separate PR.

**Comment by alfinkel** [comment]
In reference to https://github.com/cloudant/CDTDatastore/pull/116#issuecomment-85905167:  The replication tests have been updated to use the new query code.  Done in 41fb153.

**Comment by mikerhodes** [comment]
We plan to merge this after we've SQLCipher-enabled Query in the feature-encryption branch.

**Comment by mikerhodes** [comment]
I'm +1 on this :+1:

**Comment by tomblench** [comment]
+1 looks like everything has been addressed or will be addressed by other PRs

**Pull request merged**
