### PR TITLE
Enable Building CDTDatastore as a Framework

### LINKED ISSUE #194: Cannot build as a framework
(I am working from one week of total iOS, and XCode experience, so please bear with me!)

I think this project cannot build as a framework when used by a Swift project (at least with XCode 7 beta 6). The main problem is "Include of non-modular header inside framework module".

From my limited research, I gather that this issue is somewhat new (as apparently frameworks are not the only way to organize subprojects); but it is becoming more urgent, since Swift projects cannot work around it. (One can disable this compiler error; however, the disabling is not honored in Swift projects, whether by bug or design.) A clear description of the problem is here: http://inessential.com/2015/03/16/swift_blocker

In any case, it sounds like the situation XCode caught is indeed problematic and should be fixed. (My understanding is that, .h files should not import system-wide .h files--.m files should; something about a naming conflict as multiple frameworks compile together). Here is your dependency, CocoaLumberjack [struggling with the same issue][lumberjack-issue].

[lumberjack-issue]: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/544

So, modulo my naïve understanding, to be complete (except of course as a NOFIX), CDTDatastore needs to fix its own issues and then also upgrade to all dependencies when they fix theirs. This issue only applies to this project's specific build failure.

AFAICT, there is only one problem in the codebase:

    /Users/jhs/src/cloudant/CDTDatastore/Classes/common/Encryption/Attachments/CDTBlobEncryptedDataConstants.h:20:9: Include of non-modular header inside framework module 'CDTDatastore.CDTBlobEncryptedDataConstants'

### PR DESCRIPTION
**Pull request by rhyshort**
## What
Enable building CDTDatastore as a Framework.

## How
- Restructure projects to a single project with multiple targets. As a result the CDTDatastore and CDTDatastoreEncryption targets can be produced for distribution.
- Simplify podspec so there isn't a duplicate code.
- Remove TD* classes from the public interface so `CommonCrypto` includes don't stop the Framework from being built.
- Some Pre-processor tricks are required however to make CDT * Constants macros work with being in a framework. `<CommonCrypto/CommonCryptor.h>` needs to be included before CDT * Constants headers which refer to encryption.
- Created `CDTDefines.h` to contain `typedef` and `enum` declarations, to separate them from TD* classes.
- Update the Sample application to use CDTDatastore as a framework
- Include building the sample in the travis process to verify the framework can still be produced using cocoapods.
- Made header includes for deps to use the <podname/header.h> format so they can be used as a framework.

## Issues

This goes some way to making it easier to create a cordova plug-in as per #154 
Fixes #194 - using the `use_frameworks!` now results in a successful build for iOS 8+

## Notes:

- Jenkins build config needs to be updated so travis is the source of truth for the time being
- Contributing will need to updated to explain the new project layout.
- Cocoapods version 1.0.0.beta.2+ is required to make sure the build settings are correct

### CODE REVIEW

**Comment by tomblench** [comment]
It looks like `clang-format` has been run over all of the moved files which makes it difficult to see where the genuine changes are. Often I wouldn't mind but for a large PR like this it makes reviewing really hard and will also cause problems with merging any other branches.

Can we look into either undoing the changes or re-doing the moves etc from scratch, ensuring that they do not get reformatted.

**Comment by rhyshort** [comment]
Looking at each commit individually, I don't see where this has happened.

**Comment by tomblench** [comment]
@rhyshort see https://github.com/cloudant/CDTDatastore/commit/f131a71b8a22eaa679a052f517a81608c174c063

**Comment by rhyshort** [comment]
@tomblench if that's the only commit it's happen I think I can drop it then just fix the compiler errors for the missing headers again

**Comment by tomblench** [comment]
@rhyshort OK, hopefully you won't get any conflicts if you drop that commit

**Comment by rhyshort** [comment]
@tomblench done commit 1ddc8c3 just adds the header files

**Comment by tomblench** [comment]
What's going on with the copy-info.plist and copy2-info.plist files? Are they still supposed to be in the commit?

**Comment by rhyshort** [comment]
Currently yes, it was part of the target duplication, we could remove them and point at the single info.plist

**Comment by tomblench** [comment]
+1

**Comment by phatblat** [comment]
:clap:

**Pull request merged**
