### PR TITLE
47179 Add OCMock framework

### PR DESCRIPTION
**Pull request by indisoluble**
*What:*
Add a framework to `Tests` project to make it easier to create mock objects, in this case [OCMock](http://ocmock.org/).

*Why:*
If we write our own mocks and stubs, first we increase unnecessarily the number of lines in our project and also we spend a lot of time doing something that `OCMock` already offers.

*How:*
1. Add `OCMock` pod to `Tests` project
2. Delete `CDTMockEncryptionKeychainStorage` & `CDTMockEncryptionKeychainManager`
3. Use OCMock expectations and partial mocks to rewrite the tests

*Tests:*
No tests are required.

reviewer @emlaver

### CODE REVIEW

**Comment by emlaver** [comment]
It may be worth adding some comments about OCMock in the test class header.  It's difficult to understand what the OCMock methods are doing in the background (i.e. OCMVerifyAll) without having read through the OCMock reference guide.

**Comment by indisoluble** [comment]
@emlaver Comments added in 72a5f18 & 8f6e7ce

**Comment by emlaver** [comment]
Enrique and I spoke in to a bit more depth of the OCMock framework.  I asked him to add a bit more comments regarding OCMPartialMock.

**Comment by emlaver** [comment]
+1 when you've added the extra comments.

**Comment by indisoluble** [comment]
@emlaver Comments changed in af99e20 & 1959291

**Comment by emlaver** [comment]
Great, thanks.

**Comment by mikerhodes** [comment]
+1

**Pull request merged**
