### PR TITLE
Enable Replication Acceptance Tests to run against a specified CouchDB Instance

### PR DESCRIPTION
**Pull request by rhyshort**
The aim of this PR is to create a build script for the CI server to use to build the replication acceptance tests in a controlled manor. In a similar vein to the build script for sync-android.

1. Modified `CloudantReplicationTestBase` to get the URI for the test server from a new ReplicationSettings, which reads the configuration from a plist file, `ReplicationSettings.plist`.

2.  `ReplicationSettings.plist` file is modified based on environment variables by `buildplist.sh` during the 
xcode build process. 

3. `build.rb` manages the lifecycle of docker containers which run an instance of CouchDB, at the version specified by the command line argument. The script exits with the same exit code provided by  the xcodebuild command.

reviewer @mikerhodes 
reviewer @emlaver

### CODE REVIEW

**Comment by emlaver** [comment]
Rhys and I had a conversation over Slack about the background for this PR.  He sent me a link for the docker installation and the cloudantsync001 docker images.  I will be documenting the steps it takes to install and test this PR.

**Comment by mikerhodes** [comment]
Needs docs on how to use it.

Would help if commits also gave a bit more context.

**Comment by emlaver** [comment]
1.    Need to download docker: https://github.com/boot2docker/osx-installer/releases/tag/v1.5.0

                  a.    In command line:

                                               i.     Initialize docker: boot2docker init

                                              ii.     Start the docker VM and daemon: boot2docker up

                                             iii.     Run ‘export’ commands to set Docker client

                                                     i.e. export DOCKER_HOST, DOCKER_CERT_PATH, etc.

                                            iv.     Add to bash_profile: $(boot2docker shellinit)

                                             v.     If you using Cisco client (VPN), fix to use port forwarding:   
                                    https://github.com/boot2docker/boot2docker/issues/392#issuecomment-68563869

2.    Download docker images:

       a.    http://cloudantsync001.bristol.uk.ibm.com/dockerimages/cloudantsaas.tar

       b.    http://cloudantsync001.bristol.uk.ibm.com/dockerimages/couchdb1.6.tar

       c.     http://cloudantsync001.bristol.uk.ibm.com/dockerimages/couchdb2.0.tar

3.    Load docker images through command line:

       a.    ‘docker load –I couchdb2.0.tar’

4.    Set up xcpretty: sudo gem install xcpretty

5.    Run in CDTDatastore directory: ruby build.rb (optional –couch flag)

**Comment by emlaver** [comment]
Couchdb 1.6 result output:

All tests

Test Suite RA_Tests_OSX.xctest started

Attachments

    ✓ testAddLocalReplicateDeleteLocalReplicate (2.235 seconds)

    ✓ testAddLocalReplicateDeleteLocalReplicate412Retry (2.063 seconds)

    ✓ testReplicateManyLocalAttachments (1.135 seconds)

    ✓ testReplicateManyRemoteAttachments (2.376 seconds)

    ✓ testReplicateRemoteDocumentDeleteLocalCheckReplicated (3.047 seconds)

    ✓ testReplicateRemoteDocumentDeleteRemoteCheckReplicated (4.040 seconds)

    ✓ testReplicateRemoteDocumentUpdate (3.069 seconds)

    ✓ testReplicateSeveralRemoteDocumentsWithAttachments (2.062 seconds)

    ✓ testRevposIssueFixed (2.045 seconds)

ReplicationAcceptance

    ✓ test_CreateRemoteDeleteRemotePullPushCreateLocalPush (4.087 seconds)

    ✓ test_pullDocsWhileWritingOthers (99.227 seconds)

    ✓ test_pullDocsWhileWritingOthersWriteToThirdDB (205.630 seconds)

    ✓ test_pullDocsWhileWritingSame (351.425 seconds)

    ✓ test_pullDocsWhileWritingSameWriteToThirdDB (476.695 seconds)

    ✓ test_pushDocsAsWritingThem (279.809 seconds)

    ✓ test_PushResurectedDocument (1.189 seconds)

    ✓ testBasicURLConnectionChangeTracker (5.199 seconds)

    ✓ testCreateReplicationWithExtraHeaders (1.624 seconds)

    ✓ testMultiThreadedReplication (10.348 seconds)

    ✓ testPullDeleteAllPush (41.223 seconds)

    ✓ testPullErrorsWhenLocalDatabaseIsDeleted (2.169 seconds)

    ✓ testPullFilteredReplication (8.189 seconds)

    ✓ testPullLargeRevTree (45.496 seconds)

    ✓ testPullLotsOfOneRevDocuments (303.772 seconds)

    ✓ testPullLotsOfOneRevDocumentsIndexed (361.750 seconds)

    ✓ testPullModifySeveralRevsPush (940.370 seconds)

    ✓ testPushErrorsWhenLocalDatabaseIsDeleted (14.577 seconds)

    ✓ testPushFilteredReplicationAllowOne (1.181 seconds)

    ✓ testPushFilteredReplicationAllowSome (6.133 seconds)

    ✓ testPushLargeRevTree (3.342 seconds)

    ✓ testPushLotsOfOneRevDocuments (406.370 seconds)

    ✓ testPushStateAfterStopping (7.887 seconds)

    ✓ testRemoteLastSequenceValueAfterPullReplication (6.445 seconds)

    ✓ testRemoteLastSequenceValueAfterPushReplication (7.176 seconds)

    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pullDelegateDeletes (5.370 seconds)

    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pushDelegateDeletes (4.498 seconds)

    ✓ testURLConnectionChangeTrackerForRetry (15.144 seconds)

    ✓ testURLConnectionChangeTrackerWithBadCredentials (5.149 seconds)

    ✓ testURLConnectionChangeTrackerWithRealRemote (5.113 seconds)

    ✓ testURLConnectionChangeTrackerWithRealRemoteUsingAuthorizer (5.121 seconds)

Executed 40 tests, with 0 failures (0 unexpected) in 3653.776 (3653.793) seconds

**Comment by emlaver** [comment]
Couchdb 2.0 result output:

All tests

Test Suite RA_Tests_OSX.xctest started

Attachments

    ✓ testAddLocalReplicateDeleteLocalReplicate (2.189 seconds)

    ✓ testAddLocalReplicateDeleteLocalReplicate412Retry (2.055 seconds)

    ✓ testReplicateManyLocalAttachments (6.183 seconds)

    ✓ testReplicateManyRemoteAttachments (2.548 seconds)

    ✓ testReplicateRemoteDocumentDeleteLocalCheckReplicated (3.067 seconds)

    ✓ testReplicateRemoteDocumentDeleteRemoteCheckReplicated (4.048 seconds)

    ✓ testReplicateRemoteDocumentUpdate (3.060 seconds)

    ✓ testReplicateSeveralRemoteDocumentsWithAttachments (2.060 seconds)

    ✓ testRevposIssueFixed (2.044 seconds)

ReplicationAcceptance

    ✓ test_CreateRemoteDeleteRemotePullPushCreateLocalPush (4.101 seconds)

    ✓ test_pullDocsWhileWritingOthers (113.749 seconds)

    ✓ test_pullDocsWhileWritingOthersWriteToThirdDB (239.119 seconds)

    ✓ test_pullDocsWhileWritingSame (355.866 seconds)

    ✓ test_pullDocsWhileWritingSameWriteToThirdDB (435.653 seconds)

    ✓ test_pushDocsAsWritingThem (246.307 seconds)

    ✓ test_PushResurectedDocument (1.158 seconds)

    ✓ testBasicURLConnectionChangeTracker (5.184 seconds)

    ✓ testCreateReplicationWithExtraHeaders (1.620 seconds)

    ✓ testMultiThreadedReplication (4.287 seconds)

    ✓ testPullDeleteAllPush (36.688 seconds)

    ✓ testPullErrorsWhenLocalDatabaseIsDeleted (2.080 seconds)

    ✓ testPullFilteredReplication (8.158 seconds)

    ✓ testPullLargeRevTree (41.795 seconds)

    ✓ testPullLotsOfOneRevDocuments (269.050 seconds)

    ✓ testPullLotsOfOneRevDocumentsIndexed (297.357 seconds)

    ✓ testPullModifySeveralRevsPush (776.804 seconds)

    ✓ testPushErrorsWhenLocalDatabaseIsDeleted (13.172 seconds)

    ✓ testPushFilteredReplicationAllowOne (1.166 seconds)

    ✓ testPushFilteredReplicationAllowSome (6.135 seconds)

    ✓ testPushLargeRevTree (3.239 seconds)

    ✓ testPushLotsOfOneRevDocuments (361.938 seconds)

    ✓ testPushStateAfterStopping (7.510 seconds)

    ✓ testRemoteLastSequenceValueAfterPullReplication (9.440 seconds)

    ✓ testRemoteLastSequenceValueAfterPushReplication (9.311 seconds)

    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pullDelegateDeletes (7.496 seconds)

    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pushDelegateDeletes (6.438 seconds)

    ✓ testURLConnectionChangeTrackerForRetry (15.131 seconds)

    ✓ testURLConnectionChangeTrackerWithBadCredentials (10.109 seconds)

    ✓ testURLConnectionChangeTrackerWithRealRemote (5.109 seconds)

    ✓ testURLConnectionChangeTrackerWithRealRemoteUsingAuthorizer (5.107 seconds)

Executed 40 tests, with 0 failures (0 unexpected) in 3327.532 (3327.545) seconds

**Comment by emlaver** [comment]
Cloudant saas results:

All tests
Test Suite RA_Tests_OSX.xctest started
Attachments
    ✓ testAddLocalReplicateDeleteLocalReplicate (2.222 seconds)
    ✓ testAddLocalReplicateDeleteLocalReplicate412Retry (2.050 seconds)
    ✓ testReplicateManyLocalAttachments (1.142 seconds)
    ✓ testReplicateManyRemoteAttachments (2.400 seconds)
    ✓ testReplicateRemoteDocumentDeleteLocalCheckReplicated (3.051 seconds)
    ✓ testReplicateRemoteDocumentDeleteRemoteCheckReplicated (4.078 seconds)
    ✓ testReplicateRemoteDocumentUpdate (3.161 seconds)
    ✓ testReplicateSeveralRemoteDocumentsWithAttachments (2.059 seconds)
    ✓ testRevposIssueFixed (2.041 seconds)
ReplicationAcceptance
    ✓ test_CreateRemoteDeleteRemotePullPushCreateLocalPush (4.091 seconds)
    ✓ test_pullDocsWhileWritingOthers (103.780 seconds)
    ✓ test_pullDocsWhileWritingOthersWriteToThirdDB (230.897 seconds)
    ✓ test_pullDocsWhileWritingSame (374.417 seconds)
    ✓ test_pullDocsWhileWritingSameWriteToThirdDB (509.164 seconds)
    ✓ test_pushDocsAsWritingThem (434.244 seconds)
    ✓ test_PushResurectedDocument (1.291 seconds)
    ✓ testBasicURLConnectionChangeTracker (5.324 seconds)
    ✓ testCreateReplicationWithExtraHeaders (1.703 seconds)
    ✓ testMultiThreadedReplication (6.538 seconds)
    ✓ testPullDeleteAllPush (59.543 seconds)
    ✓ testPullErrorsWhenLocalDatabaseIsDeleted (4.383 seconds)
    ✓ testPullFilteredReplication (8.250 seconds)
    ✓ testPullLargeRevTree (63.696 seconds)
    ✓ testPullLotsOfOneRevDocuments (536.670 seconds)
    ✓ testPullLotsOfOneRevDocumentsIndexed (328.847 seconds)
    ✓ testPullModifySeveralRevsPush (855.120 seconds)
    ✓ testPushErrorsWhenLocalDatabaseIsDeleted (13.523 seconds)
    ✓ testPushFilteredReplicationAllowOne (1.157 seconds)
    ✓ testPushFilteredReplicationAllowSome (1.118 seconds)
    ✓ testPushLargeRevTree (3.298 seconds)
    ✓ testPushLotsOfOneRevDocuments (385.380 seconds)
    ✓ testPushStateAfterStopping (7.394 seconds)
    ✓ testRemoteLastSequenceValueAfterPullReplication (6.442 seconds)
    ✓ testRemoteLastSequenceValueAfterPushReplication (6.822 seconds)
    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pullDelegateDeletes (3.790 seconds)
    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pushDelegateDeletes (9.850 seconds)
    ✓ testURLConnectionChangeTrackerForRetry (15.111 seconds)
    ✓ testURLConnectionChangeTrackerWithBadCredentials (5.099 seconds)
    ✓ testURLConnectionChangeTrackerWithRealRemote (5.123 seconds)
    ✓ testURLConnectionChangeTrackerWithRealRemoteUsingAuthorizer (5.106 seconds)

Executed 40 tests, with 0 failures (0 unexpected) in 4019.374 (4019.392) seconds

**Comment by emlaver** [comment]
Running the build command:
xcodebuild -workspace ReplicationAcceptance.xcworkspace -scheme RA_Tests_OSX -destination 'platform=OS X' test | xcpretty

1 test failed:

All tests
Test Suite RA_Tests_OSX.xctest started
Attachments
    ✓ testAddLocalReplicateDeleteLocalReplicate (5.513 seconds)
    ✓ testAddLocalReplicateDeleteLocalReplicate412Retry (3.898 seconds)
    ✓ testReplicateManyLocalAttachments (4.753 seconds)
    ✓ testReplicateManyRemoteAttachments (29.731 seconds)
    ✓ testReplicateRemoteDocumentDeleteLocalCheckReplicated (5.187 seconds)
    ✓ testReplicateRemoteDocumentDeleteRemoteCheckReplicated (5.538 seconds)
    ✓ testReplicateRemoteDocumentUpdate (5.445 seconds)
    ✓ testReplicateSeveralRemoteDocumentsWithAttachments (6.400 seconds)
    ✓ testRevposIssueFixed (3.817 seconds)
ReplicationAcceptance
    ✓ test_CreateRemoteDeleteRemotePullPushCreateLocalPush (9.338 seconds)
    ✓ test_pullDocsWhileWritingOthers (837.498 seconds)
    ✓ test_pullDocsWhileWritingOthersWriteToThirdDB (836.681 seconds)
    ✓ test_pullDocsWhileWritingSame (832.444 seconds)
    ✓ test_pullDocsWhileWritingSameWriteToThirdDB (811.676 seconds)
    ✓ test_pushDocsAsWritingThem (384.995 seconds)
    ✓ test_PushResurectedDocument (3.564 seconds)
    ✓ testBasicURLConnectionChangeTracker (14.592 seconds)
    ✓ testCreateReplicationWithExtraHeaders (4.159 seconds)
    ✓ testMultiThreadedReplication (16.804 seconds)
    ✓ testPullDeleteAllPush (107.883 seconds)
Failing tests:
	-[ReplicationAcceptance testRemoteLastSequenceValueAfterPullReplication]
** TEST FAILED **

    ✓ testPullErrorsWhenLocalDatabaseIsDeleted (16.343 seconds)
    ✓ testPullFilteredReplication (13.889 seconds)
    ✓ testPullLargeRevTree (333.665 seconds)
    ✓ testPullLotsOfOneRevDocuments (406.641 seconds)
    ✓ testPullLotsOfOneRevDocumentsIndexed (422.020 seconds)
    ✓ testPullModifySeveralRevsPush (2709.324 seconds)
    ✓ testPushErrorsWhenLocalDatabaseIsDeleted (22.996 seconds)
    ✓ testPushFilteredReplicationAllowOne (2.275 seconds)
    ✓ testPushFilteredReplicationAllowSome (2.122 seconds)
    ✓ testPushLargeRevTree (6.983 seconds)
    ✓ testPushLotsOfOneRevDocuments (389.136 seconds)
    ✓ testPushStateAfterStopping (8.572 seconds)
    ✗ testRemoteLastSequenceValueAfterPullReplication, (([response.body.array count] == count) is true) failed - Remote db has wrong number of docs
    ✓ testRemoteLastSequenceValueAfterPushReplication (17.771 seconds)
    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pullDelegateDeletes (15.878 seconds)
    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pushDelegateDeletes (12.735 seconds)
    ✓ testURLConnectionChangeTrackerForRetry (16.171 seconds)
    ✓ testURLConnectionChangeTrackerWithBadCredentials (6.064 seconds)
    ✓ testURLConnectionChangeTrackerWithRealRemote (5.900 seconds)
    ✓ testURLConnectionChangeTrackerWithRealRemoteUsingAuthorizer (6.105 seconds)


ReplicationAcceptance
  testRemoteLastSequenceValueAfterPullReplication, (([response.body.array count] == count) is true) failed - Remote db has wrong number of docs
  /Users/estebanmlaver/Cloudant/CDTDatastore/ReplicationAcceptance/ReplicationAcceptance/ReplicationAcceptance+CRUD.m:153
  ```
    //    NSLog(@"%@", response.body.array);
    XCTAssertTrue([response.body.array count] == count, @"Remote db has wrong number of docs");
}
  ```
Executed 40 tests, with 1 failure (0 unexpected) in 8408.760 (8408.848) seconds

**Comment by gadamc** [comment]
Thanks Esteban.

Is that test consistently failing?

**Comment by mikerhodes** [comment]
@rhyshort what's the next steps given the test failure @emlaver pointed out?

**Comment by rhyshort** [comment]
I think they would be 

1. Merge this PR
2. Get ReplicationAcceptance running against all the platforms in automation 
3. Analyse any failures opening tickets and creating PRs as needed

**Comment by emlaver** [comment]
@mikerhodes @rhyshort @gadamc I'm running the xcodebuild test again to see if it's consistently failing.

**Comment by emlaver** [comment]
Looks like all tests passed this time:

All tests
Test Suite RA_Tests_OSX.xctest started
Attachments
    ✓ testAddLocalReplicateDeleteLocalReplicate (2.244 seconds)
    ✓ testAddLocalReplicateDeleteLocalReplicate412Retry (2.061 seconds)
    ✓ testReplicateManyLocalAttachments (1.172 seconds)
    ✓ testReplicateManyRemoteAttachments (2.392 seconds)
    ✓ testReplicateRemoteDocumentDeleteLocalCheckReplicated (3.054 seconds)
    ✓ testReplicateRemoteDocumentDeleteRemoteCheckReplicated (4.042 seconds)
    ✓ testReplicateRemoteDocumentUpdate (3.063 seconds)
    ✓ testReplicateSeveralRemoteDocumentsWithAttachments (2.062 seconds)
    ✓ testRevposIssueFixed (2.055 seconds)
ReplicationAcceptance
    ✓ test_CreateRemoteDeleteRemotePullPushCreateLocalPush (4.082 seconds)
    ✓ test_pullDocsWhileWritingOthers (104.149 seconds)
    ✓ test_pullDocsWhileWritingOthersWriteToThirdDB (240.372 seconds)
    ✓ test_pullDocsWhileWritingSame (393.226 seconds)
    ✓ test_pullDocsWhileWritingSameWriteToThirdDB (448.883 seconds)
    ✓ test_pushDocsAsWritingThem (253.464 seconds)
    ✓ test_PushResurectedDocument (1.170 seconds)
    ✓ testBasicURLConnectionChangeTracker (5.218 seconds)
    ✓ testCreateReplicationWithExtraHeaders (1.618 seconds)
    ✓ testMultiThreadedReplication (4.298 seconds)
    ✓ testPullDeleteAllPush (37.248 seconds)
    ✓ testPullErrorsWhenLocalDatabaseIsDeleted (3.194 seconds)
    ✓ testPullFilteredReplication (8.160 seconds)
    ✓ testPullLargeRevTree (41.449 seconds)
    ✓ testPullLotsOfOneRevDocuments (277.581 seconds)
    ✓ testPullLotsOfOneRevDocumentsIndexed (309.882 seconds)
    ✓ testPullModifySeveralRevsPush (824.386 seconds)
    ✓ testPushErrorsWhenLocalDatabaseIsDeleted (13.865 seconds)
    ✓ testPushFilteredReplicationAllowOne (1.163 seconds)
    ✓ testPushFilteredReplicationAllowSome (6.135 seconds)
    ✓ testPushLargeRevTree (3.433 seconds)
    ✓ testPushLotsOfOneRevDocuments (416.506 seconds)
    ✓ testPushStateAfterStopping (7.772 seconds)
    ✓ testRemoteLastSequenceValueAfterPullReplication (6.505 seconds)
    ✓ testRemoteLastSequenceValueAfterPushReplication (7.123 seconds)
    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pullDelegateDeletes (4.980 seconds)
    ✓ testSyncReplicationErrorsWhenLocalDatabaseDeleted_pushDelegateDeletes (5.007 seconds)
    ✓ testURLConnectionChangeTrackerForRetry (15.125 seconds)
    ✓ testURLConnectionChangeTrackerWithBadCredentials (5.121 seconds)
    ✓ testURLConnectionChangeTrackerWithRealRemote (5.120 seconds)
    ✓ testURLConnectionChangeTrackerWithRealRemoteUsingAuthorizer (5.126 seconds)


Executed 40 tests, with 0 failures (0 unexpected) in 3483.504 (3483.616) seconds

**Comment by emlaver** [comment]
+1

**Comment by mikerhodes** [comment]
Looks like we should merge +1.

**Pull request merged**
