### PR TITLE
Remove CDTDocumentBody

### PR DESCRIPTION
**Pull request by rhyshort**
Remove CDTDocumentBody class from repo, which was missed as part of the
removal of deprecated APIs.

reviewer @tomblench 
reviewer @brynh

### CODE REVIEW

**Comment by tomblench** [comment]
CDReplicatorTests will probably fail to build as they still reference this class.

There are some harmless but un-needed forward references to this class in ./Classes/common/CDTDatastore.h and ./Classes/common/CDTReplicator/CDTReplicator.h

**Comment by brynh** [comment]
Tests/Tests/DatastoreCRUD.m mentions `CDTDocumentBody`  in the strings in two assertions. These should probably be updated as they are misleading now there is no `CDTDocumentBody`.

**Comment by brynh** [comment]
+1

**Comment by tomblench** [comment]
+1

**Pull request merged**
